CI: Allow clang_plugins to be used in more CI jobs
Due to the name used to upload the test-web artificats missing the
'arch' value, a duplicate name could be generated if multiple CI
jobs use clang_plugins set to true causing artifact upload failure.

Currently not possible to use clang_plugins for these at the same time:

Linux, x86_64, Sanitizer, Clang
Linux, arm64, Sanitizer, Clang

As more CI jobs are added, more possibility of a conflict if using
clang_plugins in more situations.

If the name conflicts the following may by reported:

Error: Failed to CreateArtifact: Received non-retryable error:
Failed request: (409)
Conflict: an artifact with this name already exists on the workflow run