Meta+Toolchain: 1/2 Ignore ~/.gitconfig for reproducibility
The script was failing on my machine with the following message:

    Cloning into 'vcpkg'...
    remote: Enumerating objects: 284908, done.
    remote: Counting objects: 100% (699/699), done.
    remote: Compressing objects: 100% (335/335), done.
    remote: Total 284908 (delta 584), reused 364 (delta 364), pack-re…
    Receiving objects: 100% (284908/284908), 88.76 MiB | 16.53 MiB/s,…
    Resolving deltas: 100% (190216/190216), done.
    Updating files: 100% (12742/12742), done.
    Building vcpkg@120deac3062162151622ca4860575a33844ba10b
    fatal: 'origin' does not appear to be a git repository
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    Traceback (most recent call last):
      File "/Users/bobko/a/ladybird/./Meta/ladybird.py", line 455, in…
        main()
        ~~~~^^
      File "/Users/bobko/a/ladybird/./Meta/ladybird.py", line 162, in…
        build_dir = configure_main(platform, args.preset, args.cc, ar…
      File "/Users/bobko/a/ladybird/./Meta/ladybird.py", line 194, in…
        build_vcpkg()
        ~~~~~~~~~~~^^
      File "/Users/bobko/a/ladybird/Toolchain/BuildVcpkg.py", line 39…
        subprocess.check_call(args=["git", "fetch", "origin"], cwd=vc…
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^…
      File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python…
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['git', 'fetch', 'origin'…

The cause was that I had this in my ~/.gitconfig

    [clone]
        defaultRemoteName = o

This commit fixes the problem