LibWeb: Require spin_until call sites to respect application lifecycle
If they truly don't care that we're exiting, they must (void) result.
There should be no free lunch when shouldering event loop
responsibilities.

This change lets us get rid of some exit(0) which in turn allows GPU
resources to be explicitly released on exit, at least in the happy path.

This will matter more when we have a GPU process, but for now enjoy
far fewer of these:

fatal error: "check(0 == fHashSet.count())"